spring.application.name=BudgetBee

spring.datasource.url=jdbc:mysql://budgetbee-db-budgetbee-deploy.e.aivencloud.com:18090/defaultdb?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=BudgetBeeSecretKeyForJWTTokenGenerationMustBe256BitsLong2024
jwt.expiration=86400000

server.port=${PORT:8080}
server.servlet.context-path=/